### ISSUE TITLE
setting file:false still throws an error ( fixed )

### ISSUE THREAD

**Issue by Stefdv** [gundb/sqlite#1]
Even though i have set `file:false` it still throws an error.
Switching 2 lines in '/lib/file.js'  seems to solve this.

Before
```
var Graph = fileOpt.gun._.graph
if(!fileOpt.use){ return }
```

After 
```
if(!fileOpt.use){ return }
var Graph = fileOpt.gun._.graph
```

**Comment by amark** [comment]
fixed/merged into 0.6.1 :)
